version: "3.8"
services:
  cloudflared_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: always
    command: tunnel run c66aa0d7-0a8d-43ff-b8ed-24893900b22c
    volumes:
      - /root/.cloudflared:/home/nonroot/.cloudflared:ro
    networks:
      - planka_network
